"use strict";

const { getAuthoringGuidance } = require("./authoring-guidance.js");

const INVOCATION_INSTRUCTIONS = `Use PenEcho for explicit visual-workspace requests naming penecho, echo, canvas or 画布, e.g. “echo一下这个想法”, “penecho一下文件夹的架构”, “把你要做的修改放到canvas”. Start with required title and stable client/sessionKey; omit instanceId/canvasId for the latest opted-in browser on a new conversation, or use penecho_list_canvases for an exact opted-in connection target. Ordinary shell echo commands and unrelated canvas mentions are not triggers.`;

const WORKSPACE_INSTRUCTIONS = `${INVOCATION_INSTRUCTIONS} For “current canvas”, “this canvas”, “当前画布”, “这个画布” or selection edits, use penecho_start_session target:"current" without documentId. Retain documentId/sessionId; if bound elsewhere use a distinct stable attachment sessionKey and retain both handles. Read files/revision before editing. draw_ink uses current baseRevision, explicit #RRGGBB color and world-unit points; preserve user work and Undo. Background ink requires intended show then reread revision. Retry requestId only with identical arguments. Never guess documents by title. Reuse client/sessionKey and sessionId/documentId across turns/reconnects. Old conversations restore their original document, even closed saved documents in the background. restore defaults true; only DOCUMENT_NOT_FOUND permits replacement. Permission/storage errors remain errors; restore:false disables replacement, show defaults false. Existing documents require binding or user intent. With a selected live Canvas, use it proactively for useful visuals; skip routine edits. Keep the first useful output fast. Reuse artifact IDs. Batch meaningful public findings/blockers/completion in penecho_update_session; no progress boards, per-tool updates or idle polling. Read inbox at work checkpoints and before yielding; acknowledge done/error for quick actions, received/working only for useful waits. PenEcho starts HTTPS; browsers opt in. The stdio CLI loads CA/credential, trying known IP:port, fresh shared cache, then one-shot discovery without config edits or a daemon. Idle releases HTTP after 30 minutes, retaining stdin. Failed idle reconnect retries fresh cache then discovery; no idle CLI exit. Relaunch belongs to the AI host and must be verified. Retain client/sessionKey/documentId across processes; a fresh process must start_session with that binding. Transport IDs/PIDs are not conversation identity. A stopped client is never auto-woken. Publish final status; never send private chain-of-thought, secrets or transcripts.`;

const PAGE_PREVIEW_INSTRUCTIONS = `For one page, keep one complete scrollable Widget and update the same artifactId. Different artifactIds create separate Canvas objects; supporting/alternative roles do not merge them. Create extra page variants or section Widgets only when the user asks to compare separate deliverables. Use intent:inspect with capture:true for temporary responsive or section checks, never deliver them as extra Widgets. A capture failure may leave the Widget applied: inspect the existing artifact and reuse its ID, never create a replacement ID to retry.`;

const VISUAL_INSTRUCTIONS = `UI: deliver a usable page. ${PAGE_PREVIEW_INSTRUCTIONS} Choose page (1200×800) for desktop UI, explicit width/height for mobile, base (480×360) only for one compact idea; never combine preset size with dimensions. Explanations use clear hierarchy, meaningful diagrams/tables, concise labels and restrained semantic colors. Keep text readable at the displayed scale; reflow or simplify instead of shrinking type to fit, with no clipped controls or invented data. Use labeled native buttons/inputs with keyboard focus. Filters, tabs and toggles work locally without model calls; only explicit AI choices use data-penecho-action plus a bounded data-penecho-prompt. Label those as requests, not instant AI execution. Keep artifactId stable. Use capture:false ordinarily; for first UI review or a meaningful layout change, combine present+capture:true at basic quality, inspect returned pixels, then fix concrete defects. Stop once complete and usable; fix material errors or unreadable content, not optional cosmetic polish. On demand: penecho_get_guidance id visual-explorer for explanations; general-html for new UI, never auto-VE; math-2d/physics-2d/math-3d for science.`;

const VISUAL_TOOL_INSTRUCTIONS = `${PAGE_PREVIEW_INSTRUCTIONS} Prefer this for UI design/review: use page for desktop, explicit dimensions for mobile, and base only for one compact idea. Preserve product styling, readable type and responsive layout. Use labeled native controls with keyboard access; only explicit AI requests opt into data-penecho-action/data-penecho-prompt. Ordinary updates use capture:false; initial UI review or substantial layout changes may combine capture:true at basic quality. Read the image and fix concrete defects without recapturing unchanged work.`;

const MCP_PRESENTATION_INSTRUCTIONS = `${PAGE_PREVIEW_INSTRUCTIONS} Use presentation.intent explain|deliver|compare|review to state why an artifact is shown, and role primary|supporting|alternative to state its hierarchy. Widget and plot size presets are base 480×360, wide 992×360, tall 480×752, large 992×752, and page 1200×800. Use relativeTo with a stable artifactId for below/beside placement; compare defaults beside. Review requests attention by default, while supporting or alternative artifacts stay quiet unless reviewing. Keep the same artifactId when revising so source updates preserve the user's placement and size. Explain and compare may use Visual Explorer's infographic/comprehension structure. When reviewing or delivering an actual page design, preserve the target product UI, its page background, and real local interactions; do not wrap the page in an explanatory card. Inspect must faithfully render the supplied HTML at the requested viewport without redesign or extra labels; use page 1200×800 or explicit legacy dimensions for a mobile viewport. Use Widget intent inspect only with capture:true for one ephemeral viewport render when pixels are needed before delivery; it creates no Canvas object. Prefer one meaningful interaction over decorative controls. Widget buttons reach the client only when explicitly opted into the pull inbox with data-penecho-action="choose" and a bounded data-penecho-prompt; otherwise they are ordinary local Widget behavior, not MCP callbacks. Read and acknowledge inbox messages explicitly; no click or read automatically wakes a stopped client.`;

// Session start repeats only the compact operational reminder, not design text.
const SESSION_INSTRUCTIONS = WORKSPACE_INSTRUCTIONS;

function visualExplorerPrompt() {
  return `${getAuthoringGuidance("visual-explorer").document}\n\n## External MCP delivery\n${SESSION_INSTRUCTIONS}\n\n${MCP_PRESENTATION_INSTRUCTIONS}\n\nCreate responsive HTML/CSS/SVG with minimal JavaScript and present it with penecho_present_widget. For simple native nodes/text use penecho_draw; for bare functions use penecho_plot. Use only tools advertised by this MCP server. Read feedback before replacing an existing artifact; preserve its identity and user placement. Inspect a bounded capture after initial authoring or meaningful layout revisions when visual evidence is needed; correct concrete readability, clipping, and responsive defects. Never claim visual verification without returned pixels.`;
}

module.exports = { INVOCATION_INSTRUCTIONS, PAGE_PREVIEW_INSTRUCTIONS, MCP_PRESENTATION_INSTRUCTIONS, WORKSPACE_INSTRUCTIONS, VISUAL_INSTRUCTIONS, VISUAL_TOOL_INSTRUCTIONS, SESSION_INSTRUCTIONS, visualExplorerPrompt };
