"use strict";

const fs = require("node:fs");
const path = require("node:path");

// Keep the design authority shared with the built-in Visual Explorer. Its
// internal canvas_create/load_visual_skill instructions do not apply to MCP.
const contract = fs.readFileSync(path.join(__dirname, "../canvas-agent/visual-explorer-contract.md"), "utf8");
const designStart = contract.indexOf("Do not start from visual decoration.");
const designEnd = contract.indexOf("## PenEcho Agent source and invocation");
if (designStart < 0 || designEnd <= designStart) throw new Error("Visual Explorer design contract boundaries are missing.");
const VISUAL_EXPLORER_DESIGN = contract.slice(designStart, designEnd).trim();

const WORKSPACE_INSTRUCTIONS = `With a selected live Canvas, use it proactively for UI design/review and useful comparisons, plans, relationships or simulations. Show the smallest artifact that helps the user try, choose or understand; reuse existing work and stable IDs. A short fact, routine code edit or unchanged status needs no visual. Keep the first useful output fast. Batch meaningful public findings, blockers or completion in penecho_update_session; no progress boards, timers, idle polling or per-tool updates. Read inbox messages at active-work checkpoints and before yielding for a displayed choice. Acknowledge explicitly: a quick completed action can go directly to done; use received/working only when the wait is useful to show. A stopped client is never auto-woken. Publish final status; never send private chain-of-thought, secrets or transcripts.`;

const VISUAL_INSTRUCTIONS = `UI design: deliver a usable page preview, preserving product styling and background. Choose page (1200×800) for desktop UI, explicit width/height for mobile, base (480×360) only for one compact idea; never combine preset size with dimensions. Explanations use clear hierarchy, meaningful diagrams/tables, concise labels and restrained semantic colors. Keep text readable at the displayed scale; reflow or simplify instead of shrinking type to fit, with no clipped controls or invented data. Use labeled native buttons/inputs with keyboard focus. Filters, tabs and toggles work locally without model calls; only explicit AI choices use data-penecho-action plus a bounded data-penecho-prompt. Label those as requests, not instant AI execution. Keep artifactId stable. Use capture:false ordinarily; for first UI review or a meaningful layout change, combine present+capture:true at basic quality, inspect returned pixels, then fix concrete defects. Reuse that image; detail is for an unresolved visual question. The optional penecho_visual_explorer prompt adds the full design standard if the client exposes prompts; it is not a prerequisite.`;

const VISUAL_TOOL_INSTRUCTIONS = `Prefer this for UI design/review: use page for desktop, explicit dimensions for mobile, and base only for one compact idea. Preserve product styling, readable type and responsive layout. Use labeled native controls with keyboard access; only explicit AI requests opt into data-penecho-action/data-penecho-prompt. Ordinary updates use capture:false; initial UI review or substantial layout changes may combine capture:true at basic quality. Read the image and fix concrete defects without recapturing unchanged work.`;

const MCP_PRESENTATION_INSTRUCTIONS = `Use presentation.intent explain|deliver|compare|review to state why an artifact is shown, and role primary|supporting|alternative to state its hierarchy. Widget and plot size presets are base 480×360, wide 992×360, tall 480×752, large 992×752, and page 1200×800. Use relativeTo with a stable artifactId for below/beside placement; compare defaults beside. Review requests attention by default, while supporting or alternative artifacts stay quiet unless reviewing. Keep the same artifactId when revising so source updates preserve the user's placement and size. Explain and compare may use Visual Explorer's infographic/comprehension structure. When reviewing or delivering an actual page design, preserve the target product UI, its page background, and real local interactions; do not wrap the page in an explanatory card. Inspect must faithfully render the supplied HTML at the requested viewport without redesign or extra labels; use page 1200×800 or explicit legacy dimensions for a mobile viewport. Use Widget intent inspect only with capture:true for one ephemeral viewport render when pixels are needed before delivery; it creates no Canvas object. Prefer one meaningful interaction over decorative controls. Widget buttons reach the client only when explicitly opted into the pull inbox with data-penecho-action="choose" and a bounded data-penecho-prompt; otherwise they are ordinary local Widget behavior, not MCP callbacks. Read and acknowledge inbox messages explicitly; no click or read automatically wakes a stopped client.`;

// Session start repeats only the compact operational reminder, not design text.
const SESSION_INSTRUCTIONS = WORKSPACE_INSTRUCTIONS;

function visualExplorerPrompt() {
  return `${VISUAL_EXPLORER_DESIGN}\n\n## External MCP delivery\n${SESSION_INSTRUCTIONS}\n\n${MCP_PRESENTATION_INSTRUCTIONS}\n\nCreate responsive HTML/CSS/SVG with minimal JavaScript and present it with penecho_present_widget. For simple native nodes/text use penecho_draw; for bare functions use penecho_plot. Use only tools advertised by this MCP server. Read feedback before replacing an existing artifact; preserve its identity and user placement. Inspect a bounded capture after initial authoring or meaningful layout revisions when visual evidence is needed; correct concrete readability, clipping, and responsive defects. Never claim visual verification without returned pixels.`;
}

module.exports = { MCP_PRESENTATION_INSTRUCTIONS, WORKSPACE_INSTRUCTIONS, VISUAL_INSTRUCTIONS, VISUAL_TOOL_INSTRUCTIONS, SESSION_INSTRUCTIONS, visualExplorerPrompt };
